swagger: '2.0'
info:
  title: Staff API
  version: "1"
  description: Staff API    
host: bap-amer-south-demo1-dev.dynolab.io
basePath:
  /staff-api
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /employees:
    get:
      operationId: GetEmployees
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/employeesResponse'
      tags:
        - ProductCatalogService
  /employees/{employeeId}:
    get:
      operationId: GetEmployeeDetails
      parameters: 
        - in: path
          name: employeeId
          type: string
          required: true
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/employeeObject'
      tags:
        - ProductCatalogService
definitions:
  employeesResponse:
    type: object
    properties:
      employees:
        type: array
        items:
          $ref: '#/definitions/employeeObject'
  employeeObject:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      photo:
        type: string
